id: opecha:P009508
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD83977
  title: རིན་ཆེན་གཏེར་མཛོད་ཀྱི་དཀར་ཆག་དང་བརྒྱུད་ཡིག་དངོས་གྲུབ་སྒོ་བརྒྱ་འབྱེད་པའི་ལྡེའུ་མིག
  volume: ''
  author: ''
